[package]
name = "mcp-core"
version = "0.1.0"
authors = ["Florian Doyon <florian@talostrading.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
protobuf = "2.8.1"
itertools="0.8.0"
chrono ="0.4.9"
rkdb="0.4.0"
