# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interop.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='interop.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rinterop.proto\"\xb1\x04\n\x05Query\x12\x1d\n\x06schema\x18\x01 \x01(\x0b\x32\r.Query.Schema\x12>\n\x15instruments_by_server\x18\x02 \x03(\x0b\x32\x1f.Query.InstrumentsByServerEntry\x12#\n\x05start\x18\x03 \x01(\x0b\x32\x14.Query.TimeReference\x12!\n\x03\x65nd\x18\x04 \x01(\x0b\x32\x14.Query.TimeReference\x1aN\n\x18InstrumentsByServerEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.Query.Identifiers:\x02\x38\x01\x1a\x39\n\rTimeReference\x12\x0e\n\x04live\x18\x01 \x01(\x08H\x00\x12\x12\n\x08\x65poch_ns\x18\x02 \x01(\x04H\x00\x42\x04\n\x02is\x1a\x1c\n\x0bIdentifiers\x12\r\n\x05\x63odes\x18\x01 \x03(\t\x1a\xd7\x01\n\x06Schema\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rtimestamp_col\x18\x02 \x01(\t\x12\x16\n\x0eidentifier_col\x18\x03 \x01(\t\x12)\n\x0c\x64\x61ta_columns\x18\x04 \x03(\x0b\x32\x13.Query.Schema.Field\x1a\x37\n\x05\x46ield\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x04kind\x18\x02 \x01(\x0e\x32\x12.Query.Schema.Kind\",\n\x04Kind\x12\r\n\tTIMESTAMP\x10\x00\x12\n\n\x06SYMBOL\x10\x01\x12\t\n\x05\x46LOAT\x10\x02\x62\x06proto3')
)



_QUERY_SCHEMA_KIND = _descriptor.EnumDescriptor(
  name='Kind',
  full_name='Query.Schema.Kind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TIMESTAMP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYMBOL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOAT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=535,
  serialized_end=579,
)
_sym_db.RegisterEnumDescriptor(_QUERY_SCHEMA_KIND)


_QUERY_INSTRUMENTSBYSERVERENTRY = _descriptor.Descriptor(
  name='InstrumentsByServerEntry',
  full_name='Query.InstrumentsByServerEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Query.InstrumentsByServerEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Query.InstrumentsByServerEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=272,
)

_QUERY_TIMEREFERENCE = _descriptor.Descriptor(
  name='TimeReference',
  full_name='Query.TimeReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='live', full_name='Query.TimeReference.live', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch_ns', full_name='Query.TimeReference.epoch_ns', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='is', full_name='Query.TimeReference.is',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=274,
  serialized_end=331,
)

_QUERY_IDENTIFIERS = _descriptor.Descriptor(
  name='Identifiers',
  full_name='Query.Identifiers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='codes', full_name='Query.Identifiers.codes', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=361,
)

_QUERY_SCHEMA_FIELD = _descriptor.Descriptor(
  name='Field',
  full_name='Query.Schema.Field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Query.Schema.Field.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kind', full_name='Query.Schema.Field.kind', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=533,
)

_QUERY_SCHEMA = _descriptor.Descriptor(
  name='Schema',
  full_name='Query.Schema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Query.Schema.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_col', full_name='Query.Schema.timestamp_col', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identifier_col', full_name='Query.Schema.identifier_col', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_columns', full_name='Query.Schema.data_columns', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_QUERY_SCHEMA_FIELD, ],
  enum_types=[
    _QUERY_SCHEMA_KIND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=579,
)

_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='schema', full_name='Query.schema', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instruments_by_server', full_name='Query.instruments_by_server', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='Query.start', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='Query.end', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_QUERY_INSTRUMENTSBYSERVERENTRY, _QUERY_TIMEREFERENCE, _QUERY_IDENTIFIERS, _QUERY_SCHEMA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=579,
)

_QUERY_INSTRUMENTSBYSERVERENTRY.fields_by_name['value'].message_type = _QUERY_IDENTIFIERS
_QUERY_INSTRUMENTSBYSERVERENTRY.containing_type = _QUERY
_QUERY_TIMEREFERENCE.containing_type = _QUERY
_QUERY_TIMEREFERENCE.oneofs_by_name['is'].fields.append(
  _QUERY_TIMEREFERENCE.fields_by_name['live'])
_QUERY_TIMEREFERENCE.fields_by_name['live'].containing_oneof = _QUERY_TIMEREFERENCE.oneofs_by_name['is']
_QUERY_TIMEREFERENCE.oneofs_by_name['is'].fields.append(
  _QUERY_TIMEREFERENCE.fields_by_name['epoch_ns'])
_QUERY_TIMEREFERENCE.fields_by_name['epoch_ns'].containing_oneof = _QUERY_TIMEREFERENCE.oneofs_by_name['is']
_QUERY_IDENTIFIERS.containing_type = _QUERY
_QUERY_SCHEMA_FIELD.fields_by_name['kind'].enum_type = _QUERY_SCHEMA_KIND
_QUERY_SCHEMA_FIELD.containing_type = _QUERY_SCHEMA
_QUERY_SCHEMA.fields_by_name['data_columns'].message_type = _QUERY_SCHEMA_FIELD
_QUERY_SCHEMA.containing_type = _QUERY
_QUERY_SCHEMA_KIND.containing_type = _QUERY_SCHEMA
_QUERY.fields_by_name['schema'].message_type = _QUERY_SCHEMA
_QUERY.fields_by_name['instruments_by_server'].message_type = _QUERY_INSTRUMENTSBYSERVERENTRY
_QUERY.fields_by_name['start'].message_type = _QUERY_TIMEREFERENCE
_QUERY.fields_by_name['end'].message_type = _QUERY_TIMEREFERENCE
DESCRIPTOR.message_types_by_name['Query'] = _QUERY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), {

  'InstrumentsByServerEntry' : _reflection.GeneratedProtocolMessageType('InstrumentsByServerEntry', (_message.Message,), {
    'DESCRIPTOR' : _QUERY_INSTRUMENTSBYSERVERENTRY,
    '__module__' : 'interop_pb2'
    # @@protoc_insertion_point(class_scope:Query.InstrumentsByServerEntry)
    })
  ,

  'TimeReference' : _reflection.GeneratedProtocolMessageType('TimeReference', (_message.Message,), {
    'DESCRIPTOR' : _QUERY_TIMEREFERENCE,
    '__module__' : 'interop_pb2'
    # @@protoc_insertion_point(class_scope:Query.TimeReference)
    })
  ,

  'Identifiers' : _reflection.GeneratedProtocolMessageType('Identifiers', (_message.Message,), {
    'DESCRIPTOR' : _QUERY_IDENTIFIERS,
    '__module__' : 'interop_pb2'
    # @@protoc_insertion_point(class_scope:Query.Identifiers)
    })
  ,

  'Schema' : _reflection.GeneratedProtocolMessageType('Schema', (_message.Message,), {

    'Field' : _reflection.GeneratedProtocolMessageType('Field', (_message.Message,), {
      'DESCRIPTOR' : _QUERY_SCHEMA_FIELD,
      '__module__' : 'interop_pb2'
      # @@protoc_insertion_point(class_scope:Query.Schema.Field)
      })
    ,
    'DESCRIPTOR' : _QUERY_SCHEMA,
    '__module__' : 'interop_pb2'
    # @@protoc_insertion_point(class_scope:Query.Schema)
    })
  ,
  'DESCRIPTOR' : _QUERY,
  '__module__' : 'interop_pb2'
  # @@protoc_insertion_point(class_scope:Query)
  })
_sym_db.RegisterMessage(Query)
_sym_db.RegisterMessage(Query.InstrumentsByServerEntry)
_sym_db.RegisterMessage(Query.TimeReference)
_sym_db.RegisterMessage(Query.Identifiers)
_sym_db.RegisterMessage(Query.Schema)
_sym_db.RegisterMessage(Query.Schema.Field)


_QUERY_INSTRUMENTSBYSERVERENTRY._options = None
# @@protoc_insertion_point(module_scope)
