[package]
name = "mcp-py"
version = "0.1.0"
authors = ["Florian Doyon <florian@talostrading.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
mcp-core = {path="../mcp-core"}
protobuf="2.8.1"

[dependencies.pyo3]
version = "0.8.1"
features = ["extension-module"]